name: flutter_bloc
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  rxdart:
  cupertino_icons: ^0.1.2
  equatable: ^0.1.6
  http: 0.12.0+1
  user_repository:
     path: user_repository

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true